### ISSUE TITLE
Menus badly located

### ISSUE THREAD

**Issue by ZebZ** [ZebZ/TheGoldyIron-FiveM#17]
All the menus should be moved down to the right bottom corner.

Such as:
lscustoms
police
mechanic
_and more.._

**Comment by Slitzo3** [comment]
Fixed menus for
esx_billing
esx_animations
esx_ambulancejob
esx_mecanojob
esx_policejob

**Comment by ZebZ** [comment]
Any more that needs to be fixed?

**Comment by ZebZ** [comment]
Accessories menu needs to be moved.
