### ISSUE TITLE
Barbershop isnt taking money

### ISSUE THREAD

**Issue by Slitzo3** [ZebZ/TheGoldyIron-FiveM#20]
Barber allows you to change hairstyle/beard without having money on you

**Comment by ZebZ** [comment]
Could not reproduce this. Closing.

**Comment by ZebZ** [comment]
"When entering the barber shop, change the appearance of some skin, press enter and choose the option no, the player remains with the skin that he chose without paying."

Got some extra information.

**Comment by ZebZ** [comment]
The same issue appears with Clotheshop.

**Comment by Slitzo3** [comment]
Fixed the problem with both Barber shop & Clothes Shop
