### ISSUE TITLE
Tailor Job Not Functional

### ISSUE THREAD

**Issue by IronFeatherActual** [ZebZ/TheGoldyIron-FiveM#25]
I traveled to the spot on the map that says wool after taking the job Tailor Employee, when I arrived there was no indicator on what to do (no press this button, or colored circle to walk into or drive into. Hoping you all can fix this soon as I'd love to RP as a Tailor...

**Comment by ZebZ** [comment]
This is not a bug. This is a intended feature.

You must use the workers clothes to see  the circles.
