### ISSUE TITLE
Porche 911R Speed/Gearing

### ISSUE THREAD

**Issue by SteezyJo** [ZebZ/TheGoldyIron-FiveM#7]
Stock the Porche hits the same speed as of a fully upgraded one. Plus its a 911R and irl it should hit over 360km/h and in game its the most expensive car i just got  it and i feel like it was a waste because its alot slower on top speed than alot of cars. The gearing is really messed and and can show anyone if they want to see.

**Comment by ZebZ** [comment]
Most cars that are expensive needs to be upgraded to actualy go realy good.

**Comment by ZebZ** [comment]
And also i was the one testing the 911R so that one should be accelerating realy fast and go pretty fast when fully upgraded?

**Comment by SteezyJo** [comment]
I have the 911R fully upgraded only hits 305 if lucky

**Comment by SteezyJo** [comment]
The BMW M5 hits 280 and shouldnt even be as close as fast as the porche

**Comment by ZebZ** [comment]
Well im gona assing flameshocker to this when he have accepted my invitation the the repisitory

**Comment by ZebZ** [comment]
Though how fast are the BMW M5?

**Comment by ZebZ** [comment]
How much does the BMW M5 cost?

**Comment by SteezyJo** [comment]
I think it’s 3.3

**Comment by SteezyJo** [comment]
And I didn’t mean 280 the bmw M5 hits 380 my fault

**Comment by SteezyJo** [comment]
All I’m asking for is a little boost in speed please because I do love the car and I did spend 8 million on it

**Comment by Flameshocker** [comment]
http://prntscr.com/jje3ki well the m5 should hit 380 with some custom software ;) and http://prntscr.com/jje4di there is the porsche
