### ISSUE TITLE
Less loss on death

### ISSUE THREAD

**Issue by ZebZ** [ZebZ/TheGoldyIron-FiveM#8]
Make it so when there is no EMS online you do not lose your inventory. Though you still lose your wallet and dirty money.

**Comment by adamshcao** [comment]
You mean lose all illegal weapons and dirty money? All illegal weapons/items/cash should be taken and all legal should be kept.

**Comment by ZebZ** [comment]
No i mean you only loose the cash.

**Comment by ZebZ** [comment]
Though i think we had a better sollution for this.
